-- This file was generated automatically with a tool.
goods = {}
goods["Acid"] = {name="Acid", plural="Acid", description="A tank filled with vitriolic acid.", icon="data/textures/icons/acid.png", price=360, size=1, level=3, importance=2, illegal=false, dangerous=false, }
goods["Acron Drug"] = {name="Acron Drug", plural="Acron Drugs", description="A drug that makes the organism that uses it dependent on it.", icon="data/textures/icons/powder.png", price=6000, size=0.1, level=nil, importance=0, illegal=true, dangerous=false, }
goods["Adhesive"] = {name="Adhesive", plural="Adhesive", description="Common adhesive. Used in smaller parts where there's no space for screws.", icon="data/textures/icons/spatter.png", price=360, size=0.25, level=3, importance=4, illegal=false, dangerous=false, }
goods["Aluminium"] = {name="Aluminium", plural="Aluminium", description="A container full of pure aluminium.", icon="data/textures/icons/black-bar.png", price=200, size=1, level=0, importance=8, illegal=false, dangerous=false, }
goods["Ammunition"] = {name="Ammunition", plural="Ammunition", description="Ammunition for projectile weapons.", icon="data/textures/icons/ammo-box.png", price=3436, size=3, level=5, importance=1, illegal=false, dangerous=false, }
goods["Ammunition L"] = {name="Ammunition L", plural="Ammunition L", description="Ammunition for turrets.", icon="data/textures/icons/ammunition-l.png", price=357, size=2.5, level=4, importance=0, illegal=false, dangerous=false, }
goods["Ammunition M"] = {name="Ammunition M", plural="Ammunition M", description="Ammunition for large handheld guns.", icon="data/textures/icons/ammunition-m.png", price=357, size=1.5, level=4, importance=0, illegal=false, dangerous=false, }
goods["Ammunition S"] = {name="Ammunition S", plural="Ammunition S", description="Ammunition for small handguns.", icon="data/textures/icons/ammunition-s.png", price=357, size=0.5, level=4, importance=0, illegal=false, dangerous=false, }
goods["Anti-Grav Generator"] = {name="Anti-Grav Generator", plural="Anti-Grav Generators", description="A generator that creates a field where gravity has no effect.", icon="data/textures/icons/anti-grav-generator.png", price=57977, size=2.5, level=8, importance=0, illegal=false, dangerous=false, }
goods["Antigrav Unit"] = {name="Antigrav Unit", plural="Antigrav Units", description="This device generates antigrav fields for easier transportation of objects.", icon="data/textures/icons/tesla.png", price=22047, size=2.5, level=7, importance=4, illegal=false, dangerous=false, }
goods["Beer"] = {name="Beer", plural="Beer", description="A box of beer.", icon="data/textures/icons/beer-stein.png", price=313, size=0.5, level=4, importance=0, illegal=false, dangerous=false, }
goods["Bio Gas"] = {name="Bio Gas", plural="Bio Gas", description="Biological gas. Probably toxic.", icon="data/textures/icons/fluffy-swirl.png", price=162, size=1, level=2, importance=3, illegal=false, dangerous=false, }
goods["Body Armor"] = {name="Body Armor", plural="Body Armors", description="Exoskeleton armor for elite soldiers.", icon="data/textures/icons/kevlar-vest.png", price=85075, size=1.5, level=9, importance=0, illegal=false, dangerous=false, }
goods["Book"] = {name="Book", plural="Books", description="A book with an exciting, procedurally generated story.", icon="data/textures/icons/open-book.png", price=478, size=0.2, level=3, importance=0, illegal=false, dangerous=false, }
goods["Carbon"] = {name="Carbon", plural="Carbon", description="A container with carbon.", icon="data/textures/icons/artificial-hive.png", price=150, size=1, level=2, importance=5, illegal=false, dangerous=false, }
goods["Cattle"] = {name="Cattle", plural="Cattle", description="Cattle.", icon="data/textures/icons/bull.png", price=162, size=1.5, level=2, importance=2, illegal=false, dangerous=false, }
goods["Chemicals"] = {name="Chemicals", plural="Chemicals", description="Multitank containing all sorts of different chemicals, most of them toxic.", icon="data/textures/icons/materials-science.png", price=360, size=1, level=3, importance=6, illegal=false, dangerous=false, }
goods["Chlorine"] = {name="Chlorine", plural="Chlorine", description="A pressure container filled with pure chlorine.", icon="data/textures/icons/chlorine.png", price=150, size=1, level=0, importance=1, illegal=false, dangerous=false, }
goods["Cink"] = {name="Cink", plural="Cink", description="A medium sized crate filled with cink fragments.", icon="data/textures/icons/cink.png", price=250, size=1, level=0, importance=3, illegal=false, dangerous=false, }
goods["Clothes"] = {name="Clothes", plural="Clothes", description="Normal looking clothing.", icon="data/textures/icons/trousers.png", price=38, size=1, level=4, importance=0, illegal=false, dangerous=false, }
goods["Coal"] = {name="Coal", plural="Coal", description="Fossil fuel. Still used in some factories.", icon="data/textures/icons/thrown-charcoal.png", price=200, size=2, level=0, importance=2, illegal=false, dangerous=false, }
goods["Cocoa"] = {name="Cocoa", plural="Cocoa", description="A bag of roasted cocoa beans.", icon="data/textures/icons/coffee-mug.png", price=150, size=0.2, level=5, importance=0, illegal=false, dangerous=false, }
goods["Coffee"] = {name="Coffee", plural="Coffee", description="A bag of roasted coffee beans.", icon="data/textures/icons/coffee-beans.png", price=321, size=0.2, level=5, importance=0, illegal=false, dangerous=false, }
goods["Computation Mainframe"] = {name="Computation Mainframe", plural="Computation Mainframes", description="A high speed computer used as infrastructure for stations and ships.", icon="data/textures/icons/computer.png", price=32736, size=1, level=7, importance=0, illegal=false, dangerous=false, }
goods["Conductor"] = {name="Conductor", plural="Conductors", description="Metal staffs that are usually used for bundling electricity.", icon="data/textures/icons/unplugged.png", price=152, size=0.15, level=4, importance=9, illegal=false, dangerous=false, }
goods["Coolant"] = {name="Coolant", plural="Coolant", description="A canister full of coolant for the most common engines.", icon="data/textures/icons/snowflake-2.png", price=360, size=0.5, level=3, importance=4, illegal=false, dangerous=false, }
goods["Copper"] = {name="Copper", plural="Copper", description="A medium sized crate full of copper bars.", icon="data/textures/icons/copper.png", price=350, size=1, level=0, importance=5, illegal=false, dangerous=false, }
goods["Corn"] = {name="Corn", plural="Corn", description="A container full of corn.", icon="data/textures/icons/corn.png", price=79, size=1, level=1, importance=5, illegal=false, dangerous=false, }
goods["Crystal"] = {name="Crystal", plural="Crystals", description="Naturally grown crystals.", icon="data/textures/icons/crystal-growth.png", price=190, size=1.5, level=0, importance=2, illegal=false, dangerous=false, }
goods["Dairy"] = {name="Dairy", plural="Dairy", description="A tank full of dairy products, like yoghurt or butter.", icon="data/textures/icons/udder.png", price=7, size=1, level=3, importance=1, illegal=false, dangerous=false, }
goods["Diamond"] = {name="Diamond", plural="Diamonds", description="A hand full of diamonds. Useless unless you know where to sell them.", icon="data/textures/icons/cut-diamond.png", price=750, size=0.05, level=0, importance=3, illegal=false, dangerous=false, }
goods["Display"] = {name="Display", plural="Displays", description="A touch display for computers.", icon="data/textures/icons/checkbox-tree.png", price=6822, size=1, level=6, importance=5, illegal=false, dangerous=false, }
goods["Drill"] = {name="Drill", plural="Drills", description="Mining drill, often used in asteroid mines.", icon="data/textures/icons/drill.png", price=28538, size=20, level=7, importance=1, illegal=false, dangerous=false, }
goods["Drone"] = {name="Drone", plural="Drones", description="Unmanned little ships for everyday purpose.", icon="data/textures/icons/spoutnik.png", price=9767, size=10, level=5, importance=0, illegal=false, dangerous=false, }
goods["Electro Magnet"] = {name="Electro Magnet", plural="Electro Magnets", description="High power multi-purpose electromagnets.", icon="data/textures/icons/electro-magnet.png", price=408, size=0.75, level=5, importance=4, illegal=false, dangerous=false, }
goods["Electromagnetic Charge"] = {name="Electromagnetic Charge", plural="Electromagnetic Charges", description="One-time use charge that can set free a strong electromagnetic pulse.", icon="data/textures/icons/electromagnetic-charge.png", price=12462, size=1, level=6, importance=0, illegal=false, dangerous=false, }
goods["Electron Accelerator"] = {name="Electron Accelerator", plural="Electron Accelerators", description="A device that accelerates electrons to near lightspeed.", icon="data/textures/icons/electron-accelerator.png", price=112915, size=12, level=8, importance=0, illegal=false, dangerous=false, }
goods["Energy Cell"] = {name="Energy Cell", plural="Energy Cells", description="Small blue canisters with a high voltage charge inside them.", icon="data/textures/icons/battery-pack-alt.png", price=50, size=0.5, level=0, importance=44, illegal=false, dangerous=false, }
goods["Energy Container"] = {name="Energy Container", plural="Energy Containers", description="Bigger than energy cells, these devices can hold up to 1000x more energy.", icon="data/textures/icons/electric.png", price=948, size=4.5, level=5, importance=2, illegal=false, dangerous=false, }
goods["Energy Generator"] = {name="Energy Generator", plural="Energy Generators", description="A device that generates energy from an antimatter core.", icon="data/textures/icons/reactor.png", price=11726, size=2, level=6, importance=3, illegal=false, dangerous=false, }
goods["Energy Inverter"] = {name="Energy Inverter", plural="Energy Inverters", description="Converts electron flow into positron flow.", icon="data/textures/icons/energy-inverter.png", price=1196, size=3, level=6, importance=0, illegal=false, dangerous=false, }
goods["Energy Tube"] = {name="Energy Tube", plural="Energy Tubes", description="Long tubes that are used to transport high amounts of energy.", icon="data/textures/icons/stick-splitting.png", price=2761, size=1.5, level=5, importance=7, illegal=false, dangerous=false, }
goods["Explosive Charge"] = {name="Explosive Charge", plural="Explosive Charges", description="A military grade explosive.", icon="data/textures/icons/explosive-charge.png", price=1292, size=1.5, level=4, importance=0, illegal=false, dangerous=true, }
goods["Fabric"] = {name="Fabric", plural="Fabric", description="Raw Fabric used for clothing or bandages.", icon="data/textures/icons/bandage-roll.png", price=14, size=1, level=3, importance=2, illegal=false, dangerous=false, }
goods["Fertilizer"] = {name="Fertilizer", plural="Fertilizer", description="A tank with fertilizer, important for more exotic plants.", icon="data/textures/icons/hive.png", price=621, size=1, level=1, importance=3, illegal=false, dangerous=false, }
goods["Fish"] = {name="Fish", plural="Fish", description="A barrel full of fish.", icon="data/textures/icons/food-chain.png", price=110, size=0.5, level=2, importance=0, illegal=false, dangerous=false, }
goods["Fluorine"] = {name="Fluorine", plural="Fluorine", description="A pressure container filled with pure fluorine.", icon="data/textures/icons/fluorine.png", price=250, size=1, level=0, importance=2, illegal=false, dangerous=true, }
goods["Food"] = {name="Food", plural="Food", description="Healthy food packaged in one man portions.", icon="data/textures/icons/chicken-leg.png", price=402, size=0.5, level=4, importance=0, illegal=false, dangerous=false, }
goods["Food Bar"] = {name="Food Bar", plural="Food Bars", description="Bars of compressed food.", icon="data/textures/icons/bar.png", price=414, size=0.5, level=2, importance=0, illegal=false, dangerous=false, }
goods["Force Generator"] = {name="Force Generator", plural="Force Generators", description="A generator that creates a force field that pushes or pulls objects.", icon="data/textures/icons/force-generator.png", price=40931, size=4, level=7, importance=0, illegal=false, dangerous=false, }
goods["Fruit"] = {name="Fruit", plural="Fruits", description="A special engineered fruit, containing a wide range of important vitamins.", icon="data/textures/icons/shiny-apple.png", price=84, size=0.5, level=1, importance=2, illegal=false, dangerous=false, }
goods["Fuel"] = {name="Fuel", plural="Fuel", description="A tank with fuel for vehicles or space ships.", icon="data/textures/icons/fire.png", price=1232, size=1, level=2, importance=2, illegal=false, dangerous=false, }
goods["Fungus"] = {name="Fungus", plural="Fungi", description="A container with fungus, used for making alcohol.", icon="data/textures/icons/mushroom.png", price=45, size=1, level=3, importance=2, illegal=false, dangerous=false, }
goods["Fusion Core"] = {name="Fusion Core", plural="Fusion Cores", description="Highly advanced portable fusion generator.", icon="data/textures/icons/fusion-core.png", price=4847, size=2.5, level=6, importance=2, illegal=false, dangerous=false, }
goods["Fusion Generator"] = {name="Fusion Generator", plural="Fusion Generators", description="The bigger, better and more advanced variant of the fusion core.", icon="data/textures/icons/fusion-generator.png", price=35468, size=2.5, level=7, importance=1, illegal=false, dangerous=false, }
goods["Gauss Rail"] = {name="Gauss Rail", plural="Gauss Rail", description="A rail for immense acceleration of projectiles with magnetic fields.", icon="data/textures/icons/gauss-rail.png", price=7437, size=2, level=6, importance=1, illegal=false, dangerous=false, }
goods["Gem"] = {name="Gem", plural="Gems", description="A big gem. It's worth a lot, but you have to sell it first.", icon="data/textures/icons/saphir.png", price=400, size=0.05, level=0, importance=2, illegal=false, dangerous=false, }
goods["Glass"] = {name="Glass", plural="Glass", description="A box containing several plates of glass.", icon="data/textures/icons/metal-disc.png", price=364, size=1, level=1, importance=3, illegal=false, dangerous=false, }
goods["Gold"] = {name="Gold", plural="Gold", description="A small box containing gold bars.", icon="data/textures/icons/metal-bar.png", price=600, size=0.5, level=0, importance=8, illegal=false, dangerous=false, }
goods["Gun"] = {name="Gun", plural="Guns", description="Hand guns. Used by robots and humans.", icon="data/textures/icons/bolter-gun.png", price=1101, size=0.5, level=6, importance=1, illegal=false, dangerous=true, }
goods["Helium"] = {name="Helium", plural="Helium", description="A pressure container filled with pure helium gas.", icon="data/textures/icons/helium.png", price=50, size=1, level=0, importance=1, illegal=false, dangerous=false, }
goods["High Capacity Lens"] = {name="High Capacity Lens", plural="High Capacity Lenses", description="A focal lens designed for high capacity lasers.", icon="data/textures/icons/high-capacity-lens.png", price=4943, size=1, level=3, importance=0, illegal=false, dangerous=false, }
goods["High Pressure Tube"] = {name="High Pressure Tube", plural="High Pressure Tubes", description="Tubes that can sustain extremely high pressure. Most commonly used in factories or weapons.", icon="data/textures/icons/high-pressure-tube.png", price=1981, size=2, level=5, importance=2, illegal=false, dangerous=false, }
goods["Hydrogen"] = {name="Hydrogen", plural="Hydrogen", description="A pressure container filled with pure hydrogen.", icon="data/textures/icons/hydrogen.png", price=150, size=1, level=0, importance=2, illegal=false, dangerous=false, }
goods["Industrial Tesla Coil"] = {name="Industrial Tesla Coil", plural="Industrial Tesla Coils", description="Tesla coil used for melting of metals in factories.", icon="data/textures/icons/tesla-coil.png", price=9116, size=5.5, level=7, importance=0, illegal=false, dangerous=true, }
goods["Jewelry"] = {name="Jewelry", plural="Jewelry", description="Beautiful and very expensive jewelry.", icon="data/textures/icons/gem-chain.png", price=1218, size=0.2, level=1, importance=0, illegal=false, dangerous=false, }
goods["Laser Compressor"] = {name="Laser Compressor", plural="Laser Compressors", description="A device that can bundle energy and emit a laser beam.", icon="data/textures/icons/cog-lock.png", price=6079, size=1.5, level=6, importance=0, illegal=false, dangerous=false, }
goods["Laser Head"] = {name="Laser Head", plural="Laser Heads", description="A device used to focus laser beams.", icon="data/textures/icons/laserburn.png", price=4922, size=2, level=5, importance=1, illegal=false, dangerous=false, }
goods["Laser Modulator"] = {name="Laser Modulator", plural="Laser Modulators", description="A device that changes various properties of lasers beams passing through it.", icon="data/textures/icons/laser-modulator.png", price=14297, size=3, level=6, importance=0, illegal=false, dangerous=false, }
goods["Lead"] = {name="Lead", plural="Lead", description="A medium sized crate filled with lead bars.", icon="data/textures/icons/lead.png", price=200, size=1, level=0, importance=2, illegal=false, dangerous=false, }
goods["Leather"] = {name="Leather", plural="Leather", description="", icon="data/textures/icons/animal-hide.png", price=13, size=0.5, level=3, importance=0, illegal=false, dangerous=false, }
goods["Liquor"] = {name="Liquor", plural="Liquor", description="A box of high quality liquor.", icon="data/textures/icons/martini.png", price=2730, size=1.25, level=2, importance=0, illegal=false, dangerous=false, }
goods["Luxury Food"] = {name="Luxury Food", plural="Luxury Food", description="Luxurious food, made for the rich only.", icon="data/textures/icons/grapes.png", price=10741, size=2.5, level=6, importance=0, illegal=false, dangerous=false, }
goods["Meat"] = {name="Meat", plural="Meat", description="A box full of fresh meat.", icon="data/textures/icons/meat.png", price=13, size=0.5, level=3, importance=2, illegal=false, dangerous=false, }
goods["Medical Supplies"] = {name="Medical Supplies", plural="Medical Supplies", description="A box with everyday medical supplies containing bandages, antibiotics and germicides.", icon="data/textures/icons/overdose.png", price=2665, size=1, level=4, importance=0, illegal=false, dangerous=false, }
goods["Metal Plate"] = {name="Metal Plate", plural="Metal Plates", description="Big metal plates used for building platings of vehicles or ships.", icon="data/textures/icons/metal-scales.png", price=1089, size=3, level=4, importance=5, illegal=false, dangerous=false, }
goods["Microchip"] = {name="Microchip", plural="Microchips", description="Microchips are the most basic parts of computers.", icon="data/textures/icons/microchip.png", price=611, size=0.1, level=5, importance=7, illegal=false, dangerous=false, }
goods["Military Tesla Coil"] = {name="Military Tesla Coil", plural="Military Tesla Coils", description="A repurposed tesla coil that can shoot directed high-intensity beams of electricity.", icon="data/textures/icons/tesla-coil.png", price=9116, size=4.5, level=7, importance=0, illegal=false, dangerous=true, }
goods["Mineral"] = {name="Mineral", plural="Minerals", description="A canister full of mineral powder.", icon="data/textures/icons/cool-spices.png", price=500, size=1.5, level=0, importance=3, illegal=false, dangerous=false, }
goods["Mining Robot"] = {name="Mining Robot", plural="Mining Robots", description="A big robot used for mining in asteroid shafts where human beings would not survive.", icon="data/textures/icons/robot-golem.png", price=158663, size=8, level=9, importance=0, illegal=false, dangerous=false, }
goods["Morn Drug"] = {name="Morn Drug", plural="Morn Drugs", description="A drug that creates a very strong addiction and hallucinations.", icon="data/textures/icons/powder.png", price=5000, size=0.1, level=nil, importance=0, illegal=true, dangerous=false, }
goods["Nanobot"] = {name="Nanobot", plural="Nanobots", description="Tiny robots that are able to get into almost everything.", icon="data/textures/icons/chaingun.png", price=1292, size=0.5, level=5, importance=4, illegal=false, dangerous=false, }
goods["Neon"] = {name="Neon", plural="Neon", description="A pressure container filled with pure neon.", icon="data/textures/icons/neon.png", price=200, size=1, level=0, importance=2, illegal=false, dangerous=false, }
goods["Neutron Accelerator"] = {name="Neutron Accelerator", plural="Neutron Accelerators", description="A device that accelerates neutrons to near lightspeed.", icon="data/textures/icons/neutron-accelerator.png", price=112915, size=15, level=8, importance=0, illegal=false, dangerous=false, }
goods["Nitrogen"] = {name="Nitrogen", plural="Nitrogen", description="A pressure container filled with pure nitrogen.", icon="data/textures/icons/nitrogen.png", price=40, size=1, level=0, importance=2, illegal=false, dangerous=false, }
goods["Oil"] = {name="Oil", plural="Oil", description="A barrel of refined oil.", icon="data/textures/icons/oil-drum.png", price=490, size=1, level=1, importance=4, illegal=false, dangerous=false, }
goods["Ore"] = {name="Ore", plural="Ore", description="Raw ore containing some kind of metal.", icon="data/textures/icons/rock.png", price=70, size=2, level=0, importance=2, illegal=false, dangerous=false, }
goods["Oxygen"] = {name="Oxygen", plural="Oxygen", description="A pressure container filled with pure oxygen.", icon="data/textures/icons/oxygen.png", price=80, size=1, level=0, importance=6, illegal=false, dangerous=false, }
goods["Paint"] = {name="Paint", plural="Paint", description="A container full of paint.", icon="data/textures/icons/honeypot.png", price=448, size=1, level=4, importance=1, illegal=false, dangerous=false, }
goods["Paper"] = {name="Paper", plural="Paper", description="A big stash of paper.", icon="data/textures/icons/papers.png", price=68, size=1, level=2, importance=1, illegal=false, dangerous=false, }
goods["Plankton"] = {name="Plankton", plural="Plankton", description="A tank full of alive plankton.", icon="data/textures/icons/turtle-shell.png", price=50, size=1, level=0, importance=1, illegal=false, dangerous=false, }
goods["Plant"] = {name="Plant", plural="Plants", description="A container with soil and a wide range of green plants.", icon="data/textures/icons/sprout.png", price=21, size=1.5, level=1, importance=0, illegal=false, dangerous=false, }
goods["Plasma Cell"] = {name="Plasma Cell", plural="Plasma Cells", description="A battery that can emit a short but strong pulse of energy.", icon="data/textures/icons/cannister.png", price=150, size=0.25, level=4, importance=8, illegal=false, dangerous=false, }
goods["Plastic"] = {name="Plastic", plural="Plastic", description="A container with plastic. This is melted when used.", icon="data/textures/icons/cubeforce.png", price=137, size=0.5, level=2, importance=9, illegal=false, dangerous=false, }
goods["Platinum"] = {name="Platinum", plural="Platinum", description="A small box containing platinum bars.", icon="data/textures/icons/metal-bar.png", price=750, size=0.5, level=0, importance=8, illegal=false, dangerous=false, }
goods["Potato"] = {name="Potato", plural="Potatoes", description="A container full of potatoes.", icon="data/textures/icons/swap-bag.png", price=8, size=1, level=1, importance=1, illegal=false, dangerous=false, }
goods["Power Unit"] = {name="Power Unit", plural="Power Units", description="A big device that can create a huge amount of energy over a long time.", icon="data/textures/icons/energise.png", price=1052, size=5, level=5, importance=8, illegal=false, dangerous=false, }
goods["Processor"] = {name="Processor", plural="Processors", description="The heart of a computer, or any device that does some kind of calulcation.", icon="data/textures/icons/processor.png", price=6822, size=0.1, level=6, importance=8, illegal=false, dangerous=false, }
goods["Protein"] = {name="Protein", plural="Protein", description="Protein for quickly restoring one's energy.", icon="data/textures/icons/bar.png", price=3, size=0.1, level=4, importance=0, illegal=false, dangerous=false, }
goods["Proton Accelerator"] = {name="Proton Accelerator", plural="Proton Accelerators", description="A device that accelerates protons to near lightspeed.", icon="data/textures/icons/proton-accelerator.png", price=112915, size=15, level=8, importance=0, illegal=false, dangerous=false, }
goods["Raw Oil"] = {name="Raw Oil", plural="Raw Oil", description="A barrel of unrefined oil.", icon="data/textures/icons/oil-drum.png", price=150, size=1, level=0, importance=1, illegal=false, dangerous=false, }
goods["Rice"] = {name="Rice", plural="Rice", description="A container full of rice.", icon="data/textures/icons/powder.png", price=42, size=1, level=1, importance=2, illegal=false, dangerous=false, }
goods["Rocket"] = {name="Rocket", plural="Rockets", description="Ammunition for rocket launchers.", icon="data/textures/icons/rocket.png", price=12103, size=4, level=6, importance=0, illegal=false, dangerous=true, }
goods["Rubber"] = {name="Rubber", plural="Rubber", description="A bouncing block of rubber.", icon="data/textures/icons/cubes.png", price=1029, size=1, level=2, importance=1, illegal=false, dangerous=false, }
goods["Satellite"] = {name="Satellite", plural="Satellites", description="A satellite used for reasearch or spying.", icon="data/textures/icons/satellite.png", price=59620, size=15, level=7, importance=0, illegal=false, dangerous=false, }
goods["Scrap Metal"] = {name="Scrap Metal", plural="Scrap Metal", description="A container full of metal junk.", icon="data/textures/icons/recycle.png", price=25, size=3, level=0, importance=1, illegal=false, dangerous=false, }
goods["Semi Conductor"] = {name="Semi Conductor", plural="Semi Conductors", description="Used for building microchips and other sorts of electric things.", icon="data/textures/icons/molecule.png", price=118, size=0.1, level=4, importance=5, illegal=false, dangerous=false, }
goods["Servo"] = {name="Servo", plural="Servos", description="Little multi-purpose machines that can be used in moving parts.", icon="data/textures/icons/servo.png", price=1034, size=0.25, level=5, importance=3, illegal=false, dangerous=false, }
goods["Sheep"] = {name="Sheep", plural="Sheep", description="A sheep.", icon="data/textures/icons/sheep.png", price=146, size=1, level=2, importance=1, illegal=false, dangerous=false, }
goods["Silicium"] = {name="Silicium", plural="Silicium", description="A box with shards of silicium.", icon="data/textures/icons/groundbreaker.png", price=500, size=1, level=0, importance=3, illegal=false, dangerous=false, }
goods["Silver"] = {name="Silver", plural="Silver", description="A small box containing silver bars.", icon="data/textures/icons/metal-bar.png", price=300, size=0.5, level=0, importance=3, illegal=false, dangerous=false, }
goods["Slave"] = {name="Slave", plural="Slaves", description="An unfree life form forced to work for almost no food.", icon="data/textures/icons/slavery-whip.png", price=15000, size=1, level=nil, importance=0, illegal=true, dangerous=false, }
goods["Solar Cell"] = {name="Solar Cell", plural="Solar Cells", description="Electric cells for generating energy from sunlight.", icon="data/textures/icons/honeycomb.png", price=469, size=2, level=1, importance=1, illegal=false, dangerous=false, }
goods["Solar Panel"] = {name="Solar Panel", plural="Solar Panels", description="Solar panels that can generate electricity from sunlight.", icon="data/textures/icons/satellite.png", price=6812, size=6, level=5, importance=1, illegal=false, dangerous=false, }
goods["Solvent"] = {name="Solvent", plural="Solvent", description="A tank filled with the common industrial solvent found all over the galaxy.", icon="data/textures/icons/jerrycan.png", price=360, size=1, level=3, importance=2, illegal=false, dangerous=false, }
goods["Spices"] = {name="Spices", plural="Spices", description="A box with various little bags of spices.", icon="data/textures/icons/cool-spices.png", price=291, size=0.3, level=5, importance=1, illegal=false, dangerous=false, }
goods["Steel"] = {name="Steel", plural="Steel", description="Raw steel.", icon="data/textures/icons/i-beam.png", price=159, size=1, level=1, importance=23, illegal=false, dangerous=false, }
goods["Steel Tube"] = {name="Steel Tube", plural="Steel Tubes", description="Long multi-purpose steel tubes.", icon="data/textures/icons/steel-tube.png", price=726, size=3, level=4, importance=3, illegal=false, dangerous=false, }
goods["Targeting Card"] = {name="Targeting Card", plural="Targeting Cards", description="Multi-purpose chip with targeting software for missiles or turrets.", icon="data/textures/icons/targeting-card.png", price=10223, size=0.5, level=6, importance=1, illegal=false, dangerous=false, }
goods["Targeting System"] = {name="Targeting System", plural="Targeting Systems", description="Computer system that is able to track multiple targets.", icon="data/textures/icons/targeting-system.png", price=25721, size=0.75, level=8, importance=0, illegal=false, dangerous=false, }
goods["Tea"] = {name="Tea", plural="Tea", description="A container full of rice.", icon="data/textures/icons/leaf-swirl.png", price=53, size=0.2, level=1, importance=0, illegal=false, dangerous=false, }
goods["Teleporter"] = {name="Teleporter", plural="Teleporters", description="Short range one-man hyperspace Teleporters.", icon="data/textures/icons/teleport.png", price=34742, size=12, level=8, importance=3, illegal=false, dangerous=false, }
goods["Tools"] = {name="Tools", plural="Tools", description="A set of tools used by mechanics.", icon="data/textures/icons/hammer-nails.png", price=197, size=0.4, level=4, importance=0, illegal=false, dangerous=false, }
goods["Toxic Waste"] = {name="Toxic Waste", plural="Toxic Waste", description="A tank full of some glowing liquid. Highly toxid.", icon="data/textures/icons/biohazard.png", price=15, size=4, level=nil, importance=0, illegal=false, dangerous=true, }
goods["Transformator"] = {name="Transformator", plural="Transformators", description="A small item for transforming all kinds of energy.", icon="data/textures/icons/grenade.png", price=176, size=0.2, level=4, importance=11, illegal=false, dangerous=false, }
goods["Turbine"] = {name="Turbine", plural="Turbines", description="Multi-purpose turbine.", icon="data/textures/icons/turbine.png", price=12479, size=7.5, level=6, importance=1, illegal=false, dangerous=false, }
goods["Vegetable"] = {name="Vegetable", plural="Vegetables", description="A container with different sorts of vegetables.", icon="data/textures/icons/aubergine.png", price=21, size=1, level=1, importance=1, illegal=false, dangerous=false, }
goods["Vehicle"] = {name="Vehicle", plural="Vehicles", description="A vehicle used for planetary exploration missions.", icon="data/textures/icons/apc.png", price=67368, size=25, level=8, importance=0, illegal=false, dangerous=false, }
goods["War Robot"] = {name="War Robot", plural="War Robots", description="A big robot that is highly armed and very deadly.", icon="data/textures/icons/missile-mech.png", price=81840, size=8, level=9, importance=0, illegal=false, dangerous=true, }
goods["Warhead"] = {name="Warhead", plural="Warheads", description="Explosive heads for rockets.", icon="data/textures/icons/flame.png", price=6643, size=3, level=5, importance=1, illegal=false, dangerous=true, }
goods["Water"] = {name="Water", plural="Water", description="A tank full of clear water.", icon="data/textures/icons/gloop.png", price=30, size=1, level=0, importance=24, illegal=false, dangerous=false, }
goods["Wheat"] = {name="Wheat", plural="Wheat", description="A container full of wheat.", icon="data/textures/icons/wheat.png", price=35, size=1, level=1, importance=9, illegal=false, dangerous=false, }
goods["Wine"] = {name="Wine", plural="Wine", description="A box of wine.", icon="data/textures/icons/wine-glass.png", price=217, size=0.5, level=4, importance=1, illegal=false, dangerous=false, }
goods["Wire"] = {name="Wire", plural="Wires", description="Around 100 meters of thin wire.", icon="data/textures/icons/laser-gun.png", price=84, size=0.5, level=4, importance=6, illegal=false, dangerous=false, }
goods["Wood"] = {name="Wood", plural="Wood", description="A big block of compressed wood.", icon="data/textures/icons/log.png", price=525, size=2.5, level=1, importance=1, illegal=false, dangerous=false, }
